### ISSUE TITLE
0.4.5 && 0.4.6 broke use in nodejs / iojs for isomorphic app

### ISSUE THREAD

**Issue by iam4x** [mosch/react-avatar-editor#17]
0.4.5 and 0.4.6 broke use in nodejs / iojs for isomorphic applications:

### 0.4.5
```
Error: Cannot find module 'react-draggable'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at TOUCH (/Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:9:52)
    at Object.<anonymous> (/Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:14:2)
    at Module._compile (module.js:446:26)
    at Module._extensions..js (module.js:464:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iam4x/MNW/adserver/react-front/node_modules/babel/lib/babel/api/register/node.js:113:7)
    at Module.load (module.js:341:32)
```

### 0.4.6
```
/Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:9
        module.exports = factory(require('react'));
                         ^
ReferenceError: document is not defined
    at /Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:15:36
    at TOUCH (/Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:9:26)
    at Object.<anonymous> (/Users/iam4x/MNW/adserver/react-front/node_modules/react-avatar-editor/index.js:14:2)
    at Module._compile (module.js:446:26)
    at Module._extensions..js (module.js:464:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iam4x/MNW/adserver/react-front/node_modules/babel/lib/babel/api/register/node.js:113:7)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
```

I haven't time right now for debugging, I'll stick with `0.4.2` for now, if someone can look into it!

**Comment by mosch** [comment]
thanks for your report. do you use it in node for serverside rendering? or is there any other usecase?

**Comment by iam4x** [comment]
@mosch Yes for server side rendering, using my own boilerplate: https://github.com/iam4x/es6-react-boilerplate

**Comment by mosch** [comment]
@iam4x this should be fixed, can you validate=

**Comment by mosch** [comment]
Works in current version.

**Comment by iam4x** [comment]
@mosch Sorry didn't see the notification :)
