### ISSUE TITLE
File is not defined in 10.0.2, but 10.0.0 works fine

### ISSUE THREAD

**Issue by MikeKoval** [mosch/react-avatar-editor#191]
[1] ReferenceError: File is not defined
[1]     at Object.<anonymous> (node_modules/react-avatar-editor/dist/index.js:1:16239)
[1]     at Module._compile (module.js:571:32)
[1]     at Module._extensions..js (module.js:580:10)
[1]     at require.extensions.(anonymous function) (node_modules/babel-register/lib/node.js:152:7)
[1]     at Object._module2.default._extensions.(anonymous function) [as .js] (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:293:60)
[1]     at Module.load (module.js:488:32)
[1]     at tryModuleLoad (module.js:447:12)
[1]     at Module._load (module.js:439:3)
[1]     at Function.module._load (/node_modules/piping/lib/piping.js:218:16)
[1]     at Module.require (module.js:498:17)
[0] webpack built 375b9c9eee12bc920ebd in 25361ms

**Comment by mtlewis** [comment]
On what platform are you seeing this error? We'll need to add a fix which skips support for File images if they're not available.

**Comment by MikeKoval** [comment]
Ubuntu 16 and Mac OS Sierra

**Comment by mtlewis** [comment]
Would you mind checking to see if your issue is resolved in the preview deploy from #192 please?
