### ISSUE TITLE
Hydration error in Next.js

### ISSUE THREAD

**Issue by Penggeor** [mosch/react-avatar-editor#374]
```js
Warning: Prop `width` did not match. Server: "150" Client: "300"
    at canvas
    at a (webpack-internal:///./node_modules/react-avatar-editor/dist/index.js:1:4901)
    at div
    at eval (webpack-internal:///./node_modules/react-dropzone/dist/es/index.js:68:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at CardActions (webpack-internal:///./node_modules/@mui/material/CardActions/CardActions.js:59:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:93:82)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Card (webpack-internal:///./node_modules/@mui/material/Card/Card.js:51:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Stack (webpack-internal:///./node_modules/@mui/material/Stack/Stack.js:117:87)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Container (webpack-internal:///./node_modules/@mui/system/esm/Container/createContainer.js:121:19)
    at div
    at div
    at div
    at div
    at Layout (webpack-internal:///./src/components/Layout/index.tsx:29:23)
    at Setting (webpack-internal:///./src/pages/settings/index.tsx:49:66)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:47:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at div
    at App (webpack-internal:///./src/pages/_app.tsx:50:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:241:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:830:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:983:26) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

**Comment by this-ting** [comment]
Hey @Penggeor & @mosch 

I ran into the same issue as well. For some reason, I was only able to recreate the warning log once in StackBlitz.. it wouldn't show up after.


While I'm not too sure where the exact lines of code is causing this. Since it's a server side to client side rendering mismatch. A workaround to implement into your component is to set a toggle state, so that the pre-rendered (SSR/SSG) and the React tree that rendered during the first render in the Browser both the same empty div. After `componentDidMount` it will turn on the client side toggle to then render the `AvatarEditor` component. This ensures that `AvatarEditor` will not be  rendered in SSR, which is causing the mismatch.

[StackBlitz Demo for workaround](https://stackblitz.com/edit/nextjs-gcxncc?file=pages%2Findex.js)

```js
import React, { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import AvatarEditor from 'react-avatar-editor';

const PLACEHOLDER_IMG =
  'https://images.unsplash.com/photo-1659987012511-edde2843c69e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1856&q=80';

export default function Home() {
  const [isClientSide, setIsClientSide] = useState(false);

  useEffect(() => {
    setIsClientSide(true);
  }, []);

  if (!isClientSide) return <div />;

  return (
    <div className={styles.container}>
      <AvatarEditor
        image={PLACEHOLDER_IMG}
        width={400}
        height={200}
        border={60}
        color={[255, 255, 255, 0.6]} // RGBA
        scale={1}
        rotate={0}
      />
    </div>
  );
}


```

**Comment by mosch** [comment]
Should be fixed in 14
